### ISSUE TITLE
No 8.2 tag on github

### ISSUE THREAD

**Issue by mohe2015** [acl2/acl2#1046]
Hi,

according to [your website](https://www.cs.utexas.edu/users/moore/acl2/v8-2/HTML/installation/installation.html) the version 8.2 should already be released. But I can't find a [tag for that version on github](https://github.com/acl2/acl2/tags).
Is there a reason or did you just forget to publish a new release on github?

**Comment by MattKaufmann** [comment]
Others are far more GitHub-literate than I, but I think I can address this issue as follows.

The distribution mechanism for ACL2 plus its community books is probably unusual.  The idea is that one makes a choice: either (1) get the latest official release as a tarball, or else (2) get the latest development version from GitHub.  For (1), the installation instructions at the URL you mentioned contain a link to the tarball.  For (2), you can issue the "git clone" command also mentioned on that page.

In case someone really wants a GitHub version of the latest official release, we keep its commit hash a sort-of-secret location. near the bottom of this page:

http://www.cs.utexas.edu/users/moore/acl2/v8-2/HTML/installation/misc.html

But this is intentionally not advertised, so that changes going forward will be made to the development version only (or branches recently derived from it).

Perhaps some day we will dispense with the notion of "official release", since typically the current development version is free of known bugs.  But official releases are only made after extra-intensive testing (done by me) on at least 5 different Lisps, including variants ACL2(r) and ACL2(p), unusual targets like "make proofs" and "make ACL2_DEVEL=d", and all sorts of other things.  So official releases will probably continue to be made for awhile.

**Comment by kini** [comment]
@mohe2015 Matt's workflow involves publishing release versions to [a special fork of this repo called `acl2-devel/acl2-devel`](https://github.com/acl2-devel/acl2-devel/releases), which is intended to be more stable than the main one, `acl2/acl2`. I know it's kind of confusing, but for what it's worth, it is mentioned in the readme: https://github.com/acl2/acl2#obtaining-the-source-code

**Comment by ragerdl** [comment]
Hi Moritz,

Fundamentally, the tags are an after thought.  At your request, I've
pushed an 8.2 tag that points to the commit contained in the misc.html
link Matt sent (thanks Matt, for the pointer).

Cheers,
David

**Comment by mohe2015** [comment]
Thanks a lot for all the quick replies and the fix :+1:! I was mainly irritated that older tags existed but not the latest one. Also I was confused by a message of ACL2 (goal of NIL or something like that) as I just started yesterday and wanted to check if that also occurs on the latest release. The help for that error also didn't make sense to me but I think that's fine as the tutorials are really good and it's a completely new topic for me. Concerning https://github.com/acl2-devel/acl2-devel I would probably just publish tags in this repository and don't use that at all. But I think it's hard to change that now as some people may depend on it and I also don't know if that would be good git practice.

**Comment by MattKaufmann** [comment]
@mohe2015 Perhaps you are referring to this message about a goal of NIL:

    *** Key checkpoint under a top-level induction
        before generating a goal of NIL (see :DOC nil-goal): ***

If you have any suggestions for improving the topic nil-goal, please let us know.  We strive to make the documentation useful, and feedback from new users can be valuable.

**Comment by mohe2015** [comment]
> @MattKaufmann: If you have any suggestions for improving the topic nil-goal, please let us know.

I read it again now and I think it's fine.

By the way https://www.cs.utexas.edu/users/moore/acl2/v8-2/combined-manual/index.html?topic=ACL2____INTRODUCTORY-CHALLENGE-PROBLEM-4 may note that the proof is not complete as it doesn't check that all elements are still there.
```common-lisp
(defun collect-once (x)
  (declare (ignore x))
  nil)

(defthm main-theorem-1-about-collect-once
  (subsetp (collect-once x) x))

(defthm main-theorem-2-about-collect-once
  (not (dupsp (collect-once x))))

Q.E.D.
```
This may be a good place to teach you that you have to think about what you want to prove.

**Comment by MattKaufmann** [comment]
@mohe2015 Thanks for the feedback!  I like your idea of teaching there about thinking about what to prove.  I've updated the topic in the "bleeding edge" version of the manual, here:

http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=ACL2____INTRODUCTORY-CHALLENGE-PROBLEM-4

**Comment by kini** [comment]
Thanks to OP and Matt for improving the tutorial documentation :)

>Concerning https://github.com/acl2-devel/acl2-devel I would probably just publish tags in this repository and don't use that at all. But I think it's hard to change that now as some people may depend on it and I also don't know if that would be good git practice.

In terms of good practice, I think your suggestion (to just use this repository `acl2/acl2` and not have a separate one called `acl2-devel/acl2-devel`) is more in accordance with standard practices than what we are currently doing. But you're probably right that it's hard to change now, unfortunately.
