### ISSUE TITLE
with-output :off :all permits time$ output

### ISSUE THREAD

**Issue by bendyarm** [acl2/acl2#1293]
Consider:
```
ACL2 !>(with-output :off :all (defconst *foo1* 1))
 *FOO1*
ACL2 !>(with-output :off :all (time$ (defconst *foo2* 1)))
; (EV-REC *RETURN-LAST-ARG3* ...) took 
; 0.00 seconds realtime, 0.00 seconds runtime
; (5,616 bytes allocated).
 *FOO2*
```
According to
https://www.cs.utexas.edu/users/moore/acl2/manuals/latest/index.html?topic=ACL2____WITH-OUTPUT
`with-output :off :all` should

> Turn off all output during evaluation

but it fails to turn off the output from `time$`.

The place where this comes up for me is not with my use of `time$`, but I am writing `defconsts` forms into a book and then calling `(with-output :off :all (certify-book ...))` which calls `time$`, resulting in unwanted output.

**Comment by MattKaufmann** [comment]
Here's a two-part proposal for dealing with this Issue.  Comments are welcome.

(1) Fix :DOC with-output to replace mention of "all output" by something like "all output that can be controlled by set-inhibit-output-lst".

(2) Add a new keyword to with-output, :all!, that causes all output to be turned off (not just output controllable by set-inhibit-output-lst).  Note that this includes goal names, so :gag-mode :goals is effectively coerced to :gag-mode nil.

Implementation Notes. `(With-output :off :all! <form>)` will macroexpand in raw Lisp to `(let ((*standard-output* (make-broadcast-stream))) <form>)`.  Probably it will be implemented with return-last, in part so that top-level evaluation can do the right thing (as implemented by ev-rec and especially ev-rec-return-last).
Oh, while that works for printing, it doesn't quite work for `time$` (really, `time`) in particular!  Consider, in CCL:

    ? (let ((*standard-output* (make-broadcast-stream)))
        (time (* 3 4)))
    (* 3 4)
    took 4 microseconds (0.000004 seconds) to run.
    During that period, and with 16 available CPU cores,
         5 microseconds (0.000005 seconds) were spent in user mode
         3 microseconds (0.000003 seconds) were spent in system mode
    12
    ? 

So probably I'll bind another special variable and change time$ to be sensitive
to it.  End of Implementation Notes.

One might consider a different proposal, where instead of a new keyword :all!, the existing keyword :all turns off all behavior.  But no: I strongly prefer that the behavior of with-output be backward compatible: in particular, some may rely on tool output that is produced directly by fmt or cw.  Here's an example of existing behavior that I want to preserve.

    ACL2 !>(with-output :off :all
             (make-event (prog2$ (cw "Important message.~%")
                                 (value '(value-triple 17)))))
    Important message.
     17
    ACL2 !>

**Comment by MattKaufmann** [comment]
Binding *trace-output* too will actually inhibit output from `time`, so that's probably what I'll do for expanding `(with-output :off :all! ...)`.

    ? (let* ((*standard-output* (make-broadcast-stream))
             (*trace-output* *standard-output*))
        (time (* 3 4)))
    12
    ?

**Comment by bendyarm** [comment]
The design of `with-output` is good, where you can do `:off :all` followed by `:on something` to mean all are off except `something`.  It would be good if `:off :all!` kept that good design.  For example, right now:
```
ACL2 !>(with-output :off :all
         (make-event (prog2$ (cw "Important message.~%")
                             (value '(value-triple (/ 16 0))))))
Important message.
ACL2 !>(with-output :off :all :on error
         (make-event (prog2$ (cw "Important message.~%")
                             (value '(value-triple (/ 16 0))))))
Important message.

ACL2 Error in VALUE-TRIPLE:  The guard for the function call (UNARY-/ X),
which is (AND (ACL2-NUMBERP X) (NOT (EQUAL X 0))), is violated by the
arguments in the call (UNARY-/ 0).
See :DOC set-guard-checking for information about suppressing this
check with (set-guard-checking :none), as recommended for new users.
To debug see :DOC print-gv, see :DOC trace, and see :DOC wet.

ACL2 !>
```
If the `:all` were changed to `:all!`, it would be good if the only change to the output shown would be to not print `Important message.`.  I.e., it would be good if the following happened:
```
ACL2 !>(with-output :off :all! :on error
         (make-event (prog2$ (cw "Important message.~%")
                             (value '(value-triple (/ 16 0))))))

ACL2 Error in VALUE-TRIPLE:  The guard for the function call (UNARY-/ X),
which is (AND (ACL2-NUMBERP X) (NOT (EQUAL X 0))), is violated by the
arguments in the call (UNARY-/ 0).
See :DOC set-guard-checking for information about suppressing this
check with (set-guard-checking :none), as recommended for new users.
To debug see :DOC print-gv, see :DOC trace, and see :DOC wet.

ACL2 !>
```

More generally, if each output action were in some category that is known to `*valid-output-names*`, then `:on :all` could be defined as "turn off all except cw and trace$ output" or something like that, and `:on :all!` could be defined as "turn off all".   Another reason this would be good is that it is a step towards full control over I/O that an external agent operating ACL2 would want.

The issue about raw lisp functions writing out things that are not suppressed seems less critical to control from ACL2, but it could be useful when combining code from many different sources.  Maybe a separate `(suppress-all-output ..)` macro could do that.

**Comment by MattKaufmann** [comment]
In the "More generally" paragraph in the preceding comment, I'll assume that ":on" was intended to be ":off" both in the passage ":on :all could be defined as "turn off all except..." and in the passage ":on :all! could be defined as `turn off all'".

Currently :all has a very clear spec -- :all is short for *valid-output-names* -- and as I said, I strongly prefer that the behavior of with-output be backward compatible.  Maybe I should have said "insist" instead of "strongly prefer"; in particular, I don't want :off :all to have a new meaning in terms of cw and trace$ output; but maybe the comment about cw and trace$ (in that "More generally" paragraph) was just emphasizing that the current meaning of :off :all, which doesn't consider cw or trace$, is OK.

So let's focus on :all!.  The most reasonable meaning I see for :all! is "all output".  That includes output from cw, time$, proofs, errors, and everything else, even from raw Lisp.  As I mentioned, that can be implemented using make-broadcast-stream, by rebinding *standard-output* and *trace-output* -- actually also *error-output*.  (Technical note: I don't think it's feasible to bind two-way streams like *debug-io* in that same way, because they are used not only for output but also for input.  But I don't think that will detract significantly from the desired behavior of :all!.  A list of all streams is at https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node183.html.)

> It would be good if :off :all! kept that good design. 

I agree that it would be good to support (with-output :off :all! :on <something>), but that might be non-trivial to implement.  ACL2's output control currently has nothing to do with broadcast-streams, which are what would implement :all! (as I discussed earlier in this thread).  It might be considerably more difficult to integrate ACL2's output control with broadcast-streams -- especially when we start thinking about :stack :push and :stack :pop arguments for with-output, and perhaps aspects of ACL2 output control such as gag-mode and inhibited warnings -- than simply to turn off all output.  I had imagined not allowing other keyword arguments if :off :all! is used. But maybe it's worth considering if that's important.

> The issue about raw lisp functions writing out things that are not
> suppressed ....
> Maybe a separate (suppress-all-output ..) macro could do that.

That would presumably just be an abbreviation for `(with-output :off :all! ..)`, meaning "suppress all output".  I prefer not to consider :all! to mean "all ACL2-produced output" as opposed to "all output", since that could be confusing -- after all, output from `time$` is conceptually ACL2-produced but really comes from the Lisp implementation.

**Comment by bendyarm** [comment]
Thanks; changed `:on` to `:off` in 2 places.

> ... but maybe the comment about cw and trace$ (in that "More generally" paragraph) was just emphasizing that the current meaning of :off :all, which doesn't consider cw or trace$, is OK.

Exactly, that is why I didn't suggest changing the meaning of `:off :all`.

It seems to me that jumping to the broadcast stream implementation idea is driving the design.  But the concepts are different.  `(with-output :off :all ...)` allows selective turning back on of various kinds of output.  If we want something that turns off everything and doesn't allow selective turning on, maybe it is better to be a different name than `with-output`.  Perhaps `(without-output <form>)` with no keyword args.

That would be a useful macro, but for me right now, not so useful since I want the error output.  
More useful than that for me would be some way to turn off `time$` output.  
I don't know what all in ACL2 uses `*trace-output*` but some implementation ideas (that may or may not be feasible) are:  
1.  `(with-output :off :all+trace ..)` would send all output to `*trace-output*` instead to `/dev/null` but the `..` in the macro would be subsequently handled the same as `(with-output :off :all ..)`  
2. `(without-trace-output <some form>)`

**Comment by MattKaufmann** [comment]
Regarding:

> It seems to me that jumping to the broadcast stream implementation idea is driving the design.

You're right.  It's because that was the only way I knew of to turn off all output, which I thought at first was at issue.  And you're also right of course about time vs. time$; I missed that too.  It turns out that time$ essentially uses cw to do its printing.

So I propose to a new output type to inhibit (i.e., a new member of `*valid-output-names*`), `COMMENT`, that controls printing using cw (more precisely, the functions fmt-to-comment-window and fmt-to-comment-window!).  One could inhibit `COMMENT` output to avoid output from time$ and indeed to avoid all cw output.  Then we wouldn't need any changes to with-output.

What do you think?

That's probably all that I need to say at this point, but here are some observations that might be helpful down the road.

If there is a need for (with-output ...), that could probably be added.  Maybe instead of the broadcast-streams approach we could allow opening a channel that points to /dev/null.  That doesn't currently work, but (implementation note in case this comes up later) I think it could be arranged under-the-hood by creating a stream bound to the result of `(open "/dev/null" :direction :output :if-exists :append)`.

In case broadcast streams arise again, then regarding binding `*terminal-io*`: I was concerned because an inferior call of READ causes an error, such as: `(let ((*terminal-io* (make-broadcast-stream))) (read))`.  But the following works, for what it's worth (probably `*query-io*` and `*debug-io*` should be handled like `*standard-input*`):

    ? (let* ((i *standard-input*)
	     (*terminal-io* (make-broadcast-stream))
	     (*standard-input* i))
	(read))
    here-is-my-input
    HERE-IS-MY-INPUT
    ? (let* ((i *STANDARD-INPUT*)
	     (*terminal-io* (make-broadcast-stream))
	     (*standard-input* i))
	(cw "hi~%"))
    NIL
    ? (let* ((i *STANDARD-INPUT*)
	     (*terminal-io* (make-broadcast-stream))
	     (*standard-input* i))
	(time$ (* 3 4)))
    12
    ?

**Comment by bendyarm** [comment]
Adding `COMMENT` to `*valid-output-names*` looks good to me!  
Btw, in "If there is a need for (with-output ...), .." maybe you meant " .. (without-output ...), .."

**Comment by MattKaufmann** [comment]
Great!  OK, I plan to add COMMENT (perhaps unless I discover some unforeseen problem, of course).  Yes,, without-output (sorry); I've fixed that.

**Comment by acoglio** [comment]
This all sounds good to me.

**Comment by MattKaufmann** [comment]
COMMENT is now a valid output type (change pushed to GitHub).  I've put an item in my personal to-do list about possibly adding without-output when the time is right (personal communication from @bendyarm suggests that he doesn't yet need it).

**Comment by bendyarm** [comment]
It works great for me (commit 709d5a5526c38f47a3bba245578fb06cf7b01392), thanks!  
Closing.
