### ISSUE TITLE
Documentation doesn't show up well in Google

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#133]
_From [rage...@gmail.com](https://code.google.com/u/102895947197065323718/) on January 15, 2014 10:48:38_

It seems that fancy xdoc 6.3 and beyond aren't accessible via search engines (at least, not the version hosted at centaur).  We can see topics from 6.2 and earlier via the following search: https://www.google.com/search?q=site&#37;3Afv.centtech.com+hide But if we restrict the search to 6.3, we see no results: https://www.google.com/search?q=site&#37;3Afv.centtech.com+hide#q=site:fv.centtech.com+hide+6.3 Now, Google is notoriously bad for searching ACL2 documentation (often presenting older topics first, not providing complete results [try searching for "6.2" and "hide" in the same query]).  That being said, it'd be good if we could somehow make these topics findable via Google.  Here is a possible suggestion:

(1) Bring back the HTML directory, and have every page contain the content it used to AND
(2) In big bold letters at the top, present the user with a link to the fancy xdoc page with the topic set to the appropriate name.

This would allow users to find the page and then also easily redirect to its fancy counterpart.

We might be able to get away with leaving out the content and automatically redirecting them, but I kind of doubt it.  It's surprising that Google doesn't automatically crawl http://fv.centtech.com/acl2/latest/doc/ , so if this isn't actually broken, please close the issue.

_Original issue: http://code.google.com/p/acl2-books/issues/detail?id=132_

**Comment by ragerdl** [comment]
This still seems to be broken.  Moving back to 7.1 milestone.

Example search:

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=acl2+%22set-guard-checking%22+6.5

**Comment by sjcjoosten** [comment]
Hi David, it seems that google has an old version cached, namely:
http://webcache.googleusercontent.com/search?q=cache:FTc1UahWH0AJ:www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/COMMON-LISP____DOCUMENTATION%3Fpath%3D828+&cd=1&hl=en&ct=clnk<http://webcache.googleusercontent.com/search?q=cache:FTc1UahWH0AJ:www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/COMMON-LISP____DOCUMENTATION?path=828+&cd=1&hl=en&ct=clnk>
on January 4th, at 19.39 european time, all the links on the left were to a cs.ru.nl<http://cs.ru.nl> address. I'm guessing that this is an old error, since the current version of the page seems to work just fine. We may just have to wait for google to re-index this page.

For those whoe are site-managed, try giving Google this URL to index, including direct sublinks, as it contains a link to every page:
http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/*
(in fact, putting this link here may also help to get it crawled :-P)

**Comment by ragerdl** [comment]
Ah ha, indeed, it does seem that the cached page is out-dated... odd.  So, we shall bide our time some more.  At some point we'll want to take down the page hosted in cs.ru.nl, but I don't think it's harming anything right now?

**Comment by sjcjoosten** [comment]
I added several links from the cs.ru.nl domain to the cs.utexas.edu page. Most importantly, I'm now telling search engines that the canonical version is hosted at utexas. This should boost the utexas pages, but it is most important that those pages get fixed (it currently shows a database error).

As a final stage of phasing out the cs.ru.nl pages, I can add a http redirect, but I don't feel comfortable redirecting people to a broken page.=

**Comment by ragerdl** [comment]
Thanks for the heads up about the database error.  We had it working at some point... now just to get it working again....

**Comment by ragerdl** [comment]
FYI, http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/* is working again.  I've resubmitted it to the google index.  I'm going to leave this issue open until there's evidence of it actually working on the UTCS servers.

**Comment by ragerdl** [comment]
17 months later:

http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php

Rejoice!
