### ISSUE TITLE
LRAT proof checker and unit clauses: possibly a bug?

### ISSUE THREAD

**Issue by DennisYurichev** [acl2/acl2#1360]
Here I am again with my lousy CNF files :)
https://yurichev.com/tmp/unit_clauses/
This CNF file is UNSAT, but has unit clauses like:

```
28 0
-29 0
-30 0
-31 0
-32 0
```

PROOF generated by Kissat.

drat-trim grumbles, but produces LRAT file:

```
c WARNING: backward mode ignores deletion of (pseudo) unit clause [0] 28 0
c WARNING: backward mode ignores deletion of (pseudo) unit clause [0] -29 0
c WARNING: backward mode ignores deletion of (pseudo) unit clause [0] -30 0
c WARNING: backward mode ignores deletion of (pseudo) unit clause [0] -31 0
c WARNING: backward mode ignores deletion of (pseudo) unit clause [0] -32 0
```

ACL2 can't verify that CNF+LRAT pair:

```
HARD ACL2 ERROR in LRAT::UNIT-PROPAGATION:  unit-propagation$ has failed
for index 32230 because no formula was found for that index.
```

Probably this is due to unit clauses in the CNF, but I'm not sure.

**Comment by krobelus** [comment]
This is because the CNF file contains comments, like

	c fix_BV_NEQ

Apparently the LRAT checker does not report an error, but silently does the wrong thing.
Normally I'd write a quick patch fix this but I think I got stuck inside a Lisp macro last time I tried :(

Anyway, I have written a [wrapper script](https://github.com/krobelus/rate-experiments/blob/master/tools/bin/lrat-check) to simply remove comments from formulas before passing them to the LRAT checker. With that script, the LRAT proof is accepted.

About the warnings: drat-trim ignores deletions of unit clauses.
See our [paper](https://dl.acm.org/doi/10.1145/3372885.3373821) for some background.
The bottom line is that due to this issue, drat-trim may
1. accept an invalid DRAT proof (yet producing a valid LRAT certificate)
2. reject a valid DRAT proof

(IIRC, only 1. happens frequently on real-world proofs.)
If either is a problem, you can use the
[rate](https://github.com/krobelus/rate) proof checker,
which doesn't have this issue [^rate].

Anyway, the real fix is probably to make solvers not add the unit deletions
to the proofs -- see the "Generating Proofs without Spurious Deletions"
section in the paper; there are patches available for MiniSat-based solvers,
which is probably what you used to generate this proof?

[^rate] The name is an acronym for "rate ain't trustworthy either".

**Comment by DennisYurichev** [comment]
Yeah, the problem is in comments. Not unit clauses. Thanks!

**Comment by MattKaufmann** [comment]
Thanks @DennisYurichev -- it was helpful that you confirmed that the problem is in comments.  I've updated the parser to produce an informative error when a line starting with "c" is encountered in the cnf file.  For example, here's the error for the example you gave at the start of this Issue.

First start ACL2 and run this command:

    (include-book "projects/sat/lrat/stobj-based/run" :dir :system)

Then:

    ACL2 !>(lrat-check "SAT_lib.MOLS2_order6.cnf" "SAT_lib.MOLS2_order6.lrat")


    HARD ACL2 ERROR in LRAT::PARSE-CNF-FILE:  Line 1299 of file
    "SAT_lib.MOLS2_order6.cnf" starts with character `c', perhaps indicating
    a DIMACS comment; but such lines are not supported by this checker.

**Comment by MattKaufmann** [comment]
Oh, and also thanks to @krobelus for pointing out the comment issue!

**Comment by krobelus** [comment]
On Tue, Feb 08, 2022 at 01:44:23PM -0800, MattKaufmann wrote:
>     HARD ACL2 ERROR in LRAT::PARSE-CNF-FILE:  Line 1299 of file
>     "SAT_lib.MOLS2_order6.cnf" starts with character `c', perhaps indicating
>     a DIMACS comment; but such lines are not supported by this checker.

Very cool, thanks!
