### ISSUE TITLE
Apparent incompleteness for books/build/universal-dependency.certdep

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#1411]
Apparent incompleteness for books/build/universal-dependency.certdep

I seem to have found a case where
books/build/universal-dependency.certdep didn't do the job that I
think was intended, i.e., to force recertification of all books.  In a
nutshell, I had a book A depending on a book B, but B was recertified
after A.  I suspect that's because apply-model-2 uses a custom
makefile and B appeared to be certified at the time A's certification
was attempted (even though B's certificate was incompatible with
the current ACL2 version).

Here are details.  I don't know if anyone will want to fix this,
though.  (I don't; I'll just clean books explicitly when I need to.)

After doing a big merge for Versions 8.4 and 8.5, I decided to run
"make regression-everything" instead of "make
regression-everything-fresh", just to test
books/build/universal-dependency.certdep, which I modified when I
created Version 8.5.  (Probably I should have used
books/build/acl2-version.certdep instead, but
books/build/universal-dependency.certdep should presumably work as
well.)  It seems to have worked for the most part, but I got the
following failure for books/kestrel/big-data/packages.lisp.

```
ACL2 Error in ( INCLUDE-BOOK "projects/apply-model-2/portcullis" ...):
"/v/filer4b/v11q002/acl2space/acl2/acl2/books/projects/apply-model-2/portcullis.lisp"
was apparently certified with ACL2 Version 8.4.  The inclusion of this
book in the current ACL2 may render this ACL2 session unsound!
```

However, I checked books/build/Makefile-deps and below the line

`kestrel/big-data/packages.cert : \`

I found the expected dependency.

     projects/apply-model-2/portcullis.cert \

So presumably the problem was that
projects/apply-model-2/portcullis.cert was viewed at the time as being
up-to-date.

(By the way, I got a similar error for
books/kestrel/helpers/check-packages.lisp.)

I imagine that the problem is that
books/projects/apply-model-2/Makefile.  I'm responsible for
maintaining that directory; perhaps there's something I should do, but
I don't know what that is.

**Comment by MattKaufmann** [comment]
One correction: I said "Probably I should have used
books/build/acl2-version.certdep instead," but actually
that was updated automatically to read "ACL2 Version 8.5".

**Comment by solswords** [comment]
The problem here is a subset of a larger problem, of managing dependencies of files not managed by cert.pl on files that are managed by cert.pl.  We have a certain approach for projects/apply-model and projects/apply-model-2: those directories use the Makefile-generic approach instead of cert.pl (though I don't really know why), and books/GNUMakefile only runs make in those directories after a certain book representing all of their external dependencies (projects/apply-model[-2]-deps.cert) is built.  A problem here is that even though we wait til those dependencies are built before building in those directories, we're not correctly tracking the dependencies within those directories on files outside those directories.

The dependency of apply-model-2/portcullis on the ACL2 version is an example of this -- we know to rerun Make in apply-model-2, but we don't know that portcullis.cert is invalid because of the ACL2 version change.  But here's an example that I think makes it more clear what's going on.  The book projects/apply-model/apply.cert depends on ordinals/lexicographic-ordering-without-arithmetic.cert, as does projects/apply-model-deps.cert.  So if we modify ordinals/lexicographic-ordering-without-arithmetic.lisp, we won't run make in projects/apply-model until after we certify it again.  But suppose we've just certified the books in projects/apply-model, then we change ordinals/lex....lisp.  We'll rebuild that book and projects/apply-model-deps, then run make in projects/apply-model.  If we run with sufficient parallelism, make will try to recertify report.lisp without first recertifying apply.lisp, and fail because apply.cert is no longer valid since it depends on the old version of lex....cert, and that dependency isn't known to the Makefile in apply-model.  (The Makefiles under ex1 and ex2 actually use cert.pl to generate their dependencies, and 

A hack that could make this work, I think, would be to add in the Makefiles in those directories a dependency from portcullis.cert on (resp.) ../apply-model-deps.cert, ../apply-model-2-deps.cert.  This assumes that all the other files in those directories depend on portcullis.cert.

Or maybe we can remove all these extra makefiles and the cert_pl_exclude.  I really don't know what's in those directories that can't be handled by the usual dependency tracking.

**Comment by MattKaufmann** [comment]
Thanks, @solswords .  I think the custom Makefiles are there to support generating some .lisp files.  This morning with commit a152f211e64a3aba1debce15be7b3a8c4bccfcd4 I added the line

    ; (depends-on "build/ground-zero-theory.certdep" :dir :system)

to these books

    books/projects/apply-model/apply-prim.lisp
    books/projects/apply-model-2/apply-prim.lisp

and that solved the latest problem with those directories.  Maybe that's good enough, so I'll close this.
