### ISSUE TITLE
Slime support

### ISSUE THREAD

**Issue by Gavinok** [acl2/acl2#1446]
How viable would it be to use ACL2 with something like slime? Are you aware of previous attempts or discussion on the topic?

**Comment by MattKaufmann** [comment]
I'm not aware of any attempts to use slime with ACL2 or discussion about that.  I think most ACL2 users who want emacs support for using ACL2 (other than what they provide for themselves) load the file emacs/emacs-acl2.el that comes with ACL2.  Some who want a more modern IDE use the ACL2 Sedan.

**Comment by Gavinok** [comment]
Ah that's a shame to hear. I was pocking around in the build system to see if I could hook it in but haven't gotten deep enough to make it work. Figure it could provide a pretty great experience. Thanks for responding

**Comment by rssoc** [comment]
This issue is closed, but for both the OP and search engine users, I feel obligated to provide an update on the situation. 

I have written [a SLY extension](https://github.com/rssoc/sly-acl2) letting you interact with ACL2 in the way you probably expected from something written in CL.

If you have not heard of SLY, it's a SLIME fork with some additional features and UX improvements. In fact, it's entirely possible that the core of my extension works with SLIME just by [shadow-importing](https://github.com/rssoc/sly-acl2/blob/7d5c63c2398c1d0118a7b71badf229eac355fbb9/slynk-acl2.lisp#L196-L198) over the swank package, rather than slynk.

I should add that this extension is just groundwork for a larger, personal, effort to bring ACL2 support to ProofGeneral.

**Comment by kini** [comment]
Resurrecting ProofGeneral's ACL2 support would be great! Good luck! 🚀

**Comment by ericwhitmansmith** [comment]
It would be cool to be able to use Proof General with ACL2.

(BTW, I seem to remember that slime-mode indents IFs in a way that differs from what ACL2 users prefer [where the else-branch is indented less than the then-branch].)
