### ISSUE TITLE
Use arrow keys to navigate input in ACL2 shell

### ISSUE THREAD

**Issue by ckinateder** [acl2/acl2#1585]
I would like to see a feature where arrow keys could be used inside the shell to manipulate input/recall previous commands, instead of getting the control sequences:
```bash
ACL2 !>^[[A^[[B^[[C^[[D
```
It would be helpful to navigate around commands, i.e., to fix a typo without having to retype the whole line.

**Comment by kini** [comment]
I usually use the tool `rlwrap` (https://github.com/hanslub42/rlwrap) to accomplish what you're suggesting, FWIW.

**Comment by MattKaufmann** [comment]
Many (probably almost all) ACL2 users either run a shell inside Emacs, which has such capabilities, or use the ACL2 Sedan, ACL2s (see https://www.cs.utexas.edu/users/moore/acl2/manuals/latest/?topic=ACL2____ACL2-SEDAN).  I'm closing this issue since ACL2 won't be changing to provide direct support for editing, other than for some useful Emacs utilities available in directory books/emacs/ of the distribution, in particular, file books/emacs/emacs-acl2.el.

**Comment by ckinateder** [comment]
> I usually use the tool `rlwrap` (https://github.com/hanslub42/rlwrap) to accomplish what you're suggesting, FWIW.

This worked perfectly, thanks.
