### ISSUE TITLE
Factor out tests from the `manual` build target

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#243]
oslib/tests/dirname is broken [for me?] at the moment, but it turns out this book isn't needed in order to certify the books I use (this isn't really a surprise).  Presumably this book is transitively included in doc/top.lisp.  I don't think we should be including "tests" via the `manual` makefile target.

Of course there's a trade-off between [re]factoring our code-base and convenience when developing, and therein may be the rub (would we rather write new stuff or refactor old code that just increases organization but doesn't provide real benefit?).  That being said, I want to raise awareness and hear pushback.  Adoption of a solution would require having a second target beyond `manual` that we use to "check" that our code is correct before we check-in changes.

This is kind of similar to #224 but still a separate issue.

**Comment by acoglio** [comment]
I agree that tests should be in separate test files and that test files should not be included in the manual, or in any large "aggregator" file since tests in different files may well be incompatible when put together (e.g. they may define a function `f`).

It looks like none of the files under `[books]/oslib/tests/` is included in `[books]/oslib/top.lisp`. So perhaps that test file has been already moved out of the manual and this Issue may be closed?

**Comment by acoglio** [comment]
Given that nobody has objected or corrected my assessment above, I'm going to close this. (It can be always re-opened if needed.)

**Comment by ericwhitmansmith** [comment]
I just posted a somewhat related question on Zulip, for discussion.
