### ISSUE TITLE
Switch xdoc manual to include RTL rel10 instead of rel9

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#343]
Seems like an obvious thing to do, but there might be hiccups, so I'm making it an issue.

**Comment by MattKaufmann** [comment]
I'm doing that right now; hope to finish it today.

**Comment by MattKaufmann** [comment]
Closed with commit 353aa38f2ab1cf48b0b39d1b39c0c252fb3d077c.
I've updated the "bleeding" edge manual (in particular topic Rtl and its subtopics) at the usual place:
http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html

**Comment by ragerdl** [comment]
@MattKaufmann How come you opted to remove the documentation from rel9?  I ask, because it seems painful to do that for each release.  Oh, was it because rel10 includes rel9?  Yikes.

**Comment by MattKaufmann** [comment]
[I hope this reply via email works as advertised by github -- I don't
like having to go to the web to write these things.]

David Russinoff replaced his manual with a new version, which caused
the links computed to his manual topics to be wrong, in the rtl/rel9
ACL2+books manual.  There was no obvious way I saw to fix the
situation; it was easiest to port that computation of links etc. to
rtl/rel10, which made the most sense to me anyhow going forward.

By the way, that porting process for the manual from rtl/rel9 to
rtl/rel10 was somewhat time-consuming for me, and it may leave a
couple of issues that Russinoff wants addressed having to do with name
clashes.  It might turn out to be simplest to remove the rtl
documentation from the ACL2+books manual (though I think that would be
sad, since it provides a way to search for rtl library documentation
within the ACL2+books manual).  At any rate, I've done about all the
work I intend to do on this.

-- Matt
   Date: Wed, 11 Feb 2015 11:52:12 -0800
   From: "David L. Rager" <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>
   Cc: MattKaufmann <kaufmann@cs.utexas.edu>

   @MattKaufmann How come you opted to remove the documentation from rel9?  I ask, because it seems painful to do that for each release.  Oh, was it because rel10 includes rel9?  Yikes.

   ---

**Comment by ragerdl** [comment]
From what I can tell, my various builds are stable again.  For my future reference, I will document the two hiccups I saw:

-- `rtl/rel9/lib/doc.acl2` needed to be removed
-- I needed to do a `make clean` instead of just calling `clean.pl` to remove the outdated dependencies file

@MattKaufmann Thanks for doing most of the work on this.
