### ISSUE TITLE
Jump box fails for Rtl topic

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#344]
There doesn't seem to be a way to get to topic Rtl from the jump box.  I'm using Firefox on a Mac, with the latest "bleeding edge" manual:
http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html

**Comment by jaredcdavis** [comment]
I think this is probably happening because there is a cutoff of 20 topics in the jump-to box, and more than 20 topics that start with `RTL`.  The relevant code (from `xdoc.js`) is the `limit` field.

```
    var engine1 = new Bloodhound({
	name: 'topics',
	local: ta_data,
	limit: 20,
	datumTokenizer: function(data) {
	    return data.tokens;
	},
	queryTokenizer: Bloodhound.tokenizers.whitespace,
	sorter: function(a,b) { return alphanum(a.nicename,b.nicename); }
    });
```

Some possible fixes...

  - Maybe we can rejigger the jump-to box somehow, e.g., to display exact matches first
  - Maybe we can drop the `RTL/` prefixes from all of its topics (e.g., if rtl moves into a package)

**Comment by MattKaufmann** [comment]
I think either of the proposed solutions is fine (assuming someone wants to carry it out).  If the limit of 20 could be raised, that might be nice too.  Now that there's a scroll bar (nice!), is there a reason not to raise the limit?

**Comment by jaredcdavis** [comment]
My vague feeling is that 20 items is already a lot to scroll through.  If you're trying to find what you want among more than 20 hits in the jump-to box, then probably you're not really being specific enough, or the jump-to box just isn't providing very useful results first, or you should probably be using the search box instead.

The jump-to box results could probably be significantly improved by

  - Putting any exact matches first
  - Putting the rest of the results in "importance order"

I don't know how easy it would be to make the typeahead.js widget do these things or when I'll get to it.  If anyone wants to volunteer to look into it, that'd be great.
