### ISSUE TITLE
new jump-to box is too slow

### ISSUE THREAD

**Issue by jaredcdavis** [acl2/acl2#352]
It can seriously lag your browser if you try to type in, e.g., `vl`. 

I think I understand why this is happening and will try to work on a fix.

**Comment by MattKaufmann** [comment]
Interesting -- I just tried VL in the jump box, in firefox on a Mac,
with a manual that I put up at
http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html
only 2 hours ago, and it worked great -- no discernible delay.  So
apparently the problem is platform-specific.

(But maybe I'm misunderstanding what "lag your browser" means.)

-- Matt
   Date: Wed, 04 Mar 2015 17:16:56 -0800
   From: Jared Davis <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>

   Content-Transfer-Encoding: 7bit

   It can seriously lag your browser if you try to type in, e.g., `vl`. 

   I think I understand why this is happening and will try to work on a fix.

   ---
   Reply to this email directly or view it on GitHub:
   https://github.com/acl2/acl2/issues/352

**Comment by ragerdl** [comment]
FWIW, the "v" experiment is very slow for me on chrome in windows 7 (in excess of 10 seconds to get past the "v").

**Comment by jaredcdavis** [comment]
Yeah looks like firefox is fine, but on chrome it seems to be dog slow on
linux, windows, and mac.

On Wed, Mar 4, 2015 at 7:27 PM, David L. Rager <notifications@github.com>
wrote:

> FWIW, the "v" experiment is very slow for me on chrome in windows 7 (in
> excess of 10 seconds to get past the "v").
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/352#issuecomment-77288202>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/
