### ISSUE TITLE
cert seems broken by autoloading of .port files; new cert_param might help

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#371]
The automatic loading of .port files seems to break pcert.
I got a "convert" failure for
books/workshops/2011/verbeek-schmaltz/sources/correctness.pcert1
for which I think loading a .port file was the cause.

I tried adding (ubt! 1) to cert.acl2 in that directory, but I don't
think it helps, given the following from correctness.pcert1.out.
(It's difficult to tell for sure, because the failure is
intermittent.)

    (ubt! 1) ; don't load .port files, thus avoiding error in creating .pcert1 files

    ; Prevent reset-prehistory while loading .port files
    (acl2::assign acl2::skip-reset-prehistory acl2::t)
    ; portculli for included books:
    (acl2::ld "invariants3.port" :ld-missing-input-ok t)

At any rate, it would be good to have SOME convenient mechanism, such
as a cert_param, for avoiding loading .port files.  Actually, if
cert_param pcert=1 is present, maybe cert.pl would be willing to avoid
loading .port files?

**Comment by solswords** [comment]
I don't think I've seen this particular failure before, and I'm just
speculating about the cause, but maybe the problem is that each book's port
file gets written once for each certification pass done on the book, so
perhaps sometimes another book is trying to read a .port file when it's
simultaneously being written?  If this is the problem, would it be workable
to avoid writing out the .port file after the first pass?

It's not that it'd be hard or particularly objectionable to have a per-book
or per-directory setting to avoid loading .port files, but if I understand
the problem correctly, I don't think this is a situation where you
shouldn't want to load them -- it's just that something's screwing up the
port files we're loading.  Maybe there are situations where you don't want
to load the .port files, but I think those are (or maybe should be) pretty
rare -- if you're including a book, you should define all the packages that
book depends on, which loading the .port files accomplishes pretty
directly. (If there are other things besides packages, defconsts in support
of packages, and add-include-book-dirs in your portcullis, why?)

 - Sol

**Comment by MattKaufmann** [comment]
Fixed in 6cfc06453017b689e25739f21e782598e64965f3.  The solution was to avoid writing .port files when doing any step of provisional certification (unless an explicit :write-port argument is given to certify-book).

I think that Sol's analysis provides one way things can go wrong when .port files are used with provisional certification. An even simpler way, I think, is for a .port file to be present when doing the "Convert" step (to create a .pcert1 file) that wasn't there for the corresponding earlier "Create" step (to create a .pcert0 file).  I think that's the error I saw.  Anyhow,this change should fix both -- though I wasn't able to re-create the error, so I wasn't really able to test the fix.
