### ISSUE TITLE
Autoins function returns arguments in reverse order

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#427]
Hi @solswords ,

Do you mind if I change the SV[ex] code that generates the autoins-fn to return the inputs in the same order as they're given?  The fact that it reverses their order is breaking a bunch of my proofs since we don't use auto-ins everywhere and the matching now fails.

I can imagine that such a change might break a lot of centaur code, but it seems like this is the right thing to do if we can afford to deal with the pain.

David

**Comment by solswords** [comment]
It's probably ok.  If you make a pull request I'll check it against our
existing stuff & see how it goes.

**Comment by solswords** [comment]
OK, this is a pretty harmless patch, but it seems bad to depend on input variables occurring in a certain order.  This is already pretty implementation-detail-dependent and would be even more unpredictable for things where, e.g., the same input variable occurs as the driver for multiple wires.  The reason for having autoins, autoins-alist, autohyps, etc. be functions rather than macros was to avoid exposing things like the particular cons structure of the alist in proofs, or at least allowing the opportunity to factor these proofs out separately rather than enabling these functions inside a big proof.  If it helps, it should be pretty easy to prove that svtv-run has an alist-equiv congruence over the input alist.

I know backward compatibility is desirable, so if this patch really helps then it's ok, but I don't think I'd hesitate to do something that would change the order again if there was a reason to do so.  I.e., I don't consider the order of the alist produced by svtv-autoins to be part of the stable API (if anything is).

**Comment by ragerdl** [comment]
Indeed, I think you were a bigger fan of autoins in the past than I was (I have my reasons for preferring not to use them, but I'll spare everyone).  The "good" news is that using autoins now is basically required, because otherwise very little matches when you go perform rewriting with your lemmas.  So, in a way, this patch is (mostly?) unnecessary.  That being said, I still think it's a nice hygiene improvement to reverse the list, so I'm still a proponent of the patch.  I'm good with the idea that autoins is the API, not the exact alist structure, and I agree that the new autoins interface decreases the chances of mismatches based on the order of the alist pairs.

You mentioned auto-hyps.  I'm moderately convinced that auto-hyps is kind of broken at the moment, but I don't have a clear example beyond issue #430 that explains that reasoning.


BTW, working with this framework is really interesting, and y'all have done an amazing and phenomenal job.  I'm sure some of this feedback can be considered unnecessary (or maybe even wrong), but part of the point of sharing code is to get feedback, so I shall keep chiming in with mn reaction unless someone asks me to stop.

**Comment by ragerdl** [comment]
Fixed in 

https://github.com/acl2/acl2/commit/6f7a4533c8b80676a1a1d6e4838e161241d27a0c
