### ISSUE TITLE
Contribute books/projects/masc

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#489]
@russinoff writes

```
I have a directory that I'd like to upload to books/projects/masc. I'm a
little confused about the business of regression testing.

The directory contains the following subdirectories:

(1) A Flex/Bison parser for the MASC language, which a representation of a
program as a set of S-expressuons

(2) An ACL2 program that converts these S-expressions to an executable ACL2
model of the MASC program

(3) A script that runs the parser, generates the ACL2 model, and some other
stuff.

(4) A couple of simple illustrations, including the imul example that was
described in our 2014 workshop paper, along with the script for the
correctness proof.

So I don't know what it means to test this thing for regression. I guess
my intention is that an interested party would copy this directory
somewhere and follow my instructions for compiling the parser, running the
examples, and certifying the proof script.

So I copied this directory into my local acl2/books directory and just for
kicks, ran the regression thing. It failed, and I don't know what this
means.
```

**Comment by ragerdl** [comment]
What is "the regression thing?"  What's the failure message you're receiving?  While it's good to contribute all four of these parts to the repository, It doesn't seem to me that you need all four of these components to be part of the "acl2 regression test."  Any file that ends with .lisp will automatically be made by cert.pl.

If I were trying to contribute a lexx/yacc project, as in (1), I think I'd have a `Makefile` that ensured (1), (2), (3), and (4) built in a sensible way.  You can see examples of such approaches in `projects`, specifically `milawa`.

This is somewhat new territory for us, so it might take a couple different attempts to settle on something that works well.

**Comment by russinoff** [comment]
Here is the relevant line in make-regression.log:

make[1]: *** No rule to make target
`projects/masc/examples/imul/imul.lisp', needed by
`projects/masc/examples/imul/imul.cert'.

This makes no sense to me because these are the only files in
`projects/masc/examples/imul/:

command_script.tcl  imul.cpp  imul.vs  proof.lisp  tests.txt

**Comment by MattKaufmann** [comment]
I think there are examples like that in the regression suite, such as:

workshops/2003/kaufmann/support/

But it can be messy to deal with them (e.g., search for 2003/kaufmann
in books/GNUmakefile).  Perhaps it's best simply to exclude
projects/masc/examples by putting a cert_pl_exclude file there.  It's
nice to have as many tests as possible (at least from my pespective),
but maybe sometimes it's not worth the trouble.

-- Matt
   Date: Fri, 14 Aug 2015 13:29:10 -0700
   From: russinoff <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>

   Here is the relevant line in make-regression.log:

   make[1]: *** No rule to make target
   `projects/masc/examples/imul/imul.lisp', needed by
   `projects/masc/examples/imul/imul.cert'.

   This makes no sense to me because these are the only files in
   `projects/masc/examples/imul/:

   command_script.tcl  imul.cpp  imul.vs  proof.lisp  tests.txt


   On Fri, Aug 14, 2015 at 2:49 PM, David L. Rager <notifications@github.com>
   wrote:

   > What is "the regression thing?" What's the failure message you're
   > receiving? While it's good to contribute all four of these parts to the
   > repository, It doesn't seem to me that you need all four of these
   > components to be part of the "acl2 regression test." Any file that ends
   > with .lisp will automatically be made by cert.pl.
   >
   > If I were trying to contribute a lexx/yacc project, as in (1), I think I'd
   > have a Makefile that ensured (1), (2), (3), and (4) built in a sensible
   > way. You can see examples of such approaches in projects, specifically
   > milawa.
   >
   > This is somewhat new territory for us, so it might take a couple different
   > attempts to settle on something that works well.
   >
   > =E2=80=94
   > Reply to this email directly or view it on GitHub
   > <https://github.com/acl2/acl2/issues/489#issuecomment-131218467>.
   >


   ---
   Reply to this email directly or view it on GitHub:
   https://github.com/acl2/acl2/issues/489#issuecomment-131231843=

**Comment by ragerdl** [comment]
Does `proof.lisp` include a book named `imul`?  I think that might generate such an error message.  The error message also doesn't make sense to me.

If I have time later this afternoon or this weekend, I'll take a look.  If you're okay with preventing yourself from making pull requests for up to a week (that's how long I think it might take for me to debug this), you can (1) commit your changes locally, (2) push those commits to your repository, and then (3) I can checkout your repository have a look and (4) fix the issue in a reasonable way.

Steps (1) and (2) are identical to the steps to make a pull request, except that you don't wait for the books to build, and you don't actually make a pull request.

**Comment by russinoff** [comment]
Ah, I see,  Yes, proof.lisp includes imul.lisp, which doesn't exist.  This
is by design.  I include instructions for the user to invoke the MASC-ACL2
translator to generate and certify imul.lisp and then certify proof.lisp.

I've pushed it into my local repository as you suggested.  I think it makes
sense to add the file suggested by Shamu to make the whole directory immune
to regression testing.  See what you think.

**Comment by ragerdl** [comment]
Okay, I've added the aforementioned cert_pl_exclude file.  I haven't tested it beyond making sure that its addition doesn't break the repository.  You should be able to update your local copy and re-push to `russinoff/acl2` `master` once you're ready.  And then create a pull request.

**Comment by russinoff** [comment]
Please explain.  How do I update my local copy?

**Comment by ragerdl** [comment]
Hi David,

The way you usually do.  It's step (B) of 

http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/?topic=ACL2____GITHUB-COMMIT-CODE-USING-PULL-REQUESTS

Cheers,
David

**Comment by russinoff** [comment]
Now something else is broken.  "git fetch --all"works, but when I try "git
merge remotes/upstream/master" or "git commit -a", it hangs forever.  Most
frustrating.

**Comment by ragerdl** [comment]
Okay, I'd use the following two commands to try to figure out what's going
on.
`git status`
`git add <path-and-filename>`

If there was a merge conflict, `git status` _might_ list them, but if not,
you'll need to grep for `====` to find the conflicts.  Once you resolve the
conflicts, you `git add ...` the file.  And then you can `git commit`
(without the `-a` flag, which means "add all files that have changes" --
but that flag is unnecessary because you will have added all of the files
already).

How long is "forever"?  If it's less than five minutes, you might just need
to wait.

**Comment by russinoff** [comment]
I think I've pushed the masc directory into my repository.  Would you see
if it looks all right?

**Comment by ragerdl** [comment]
Hi @russinoff,

I've modified my Makefile as follows:

```
export ACL2?=/home/dlrager/sw/acl2-dmr/ccl-saved_acl2
export MASC?=/home/dlrager/sw/acl2-dmr/books/projects/masc
```

And I'm running make and obtain the following error.  I can probably chase
it down, but I'd rather just ask:

```
bash-4.1$ make
(cd src; make all)
make[1]: Entering directory
`/home/dlrager/sw/acl2-dmr/books/projects/masc/src'
echo -e
"#!/bin/bash\n\nMASC=/home/dlrager/sw/acl2-dmr/books/projects/masc\nACL2=/home/dlrager/sw/acl2-dmr/ccl-saved_acl2"
| cat - masc-skel > masc
install -m 755 masc /home/dlrager/sw/acl2-dmr/books/projects/masc/bin
bison -d -v parser.y
flex parser.l
g++ -g -o ../bin/parse parser.tab.c lex.yy.c output.c main.c  -lfl
/usr/bin/ld: cannot open output file ../bin/parse: Not a directory
collect2: ld returned 1 exit status
make[1]: *** [../bin/parse] Error 1
make[1]: Leaving directory
`/home/dlrager/sw/acl2-dmr/books/projects/masc/src'
make: *** [all] Error 2
bash-4.1$
```

To my knowledge, I don't have systemC installed, but I'm not sure it's
necessary for this step.  Any idea where `../bin/parse` is supposed to be?
There's a file named `bin` in the masc directory that looks to be some sort
of configuration file.

David

**Comment by ragerdl** [comment]
The problem is that a `bin` file is being created for some reason, instead of a `bin` directory.

**Comment by ragerdl** [comment]
Ah, the problem is that the author assumes `bin` to be part of the repository.  Since empty directories don't exist in git repositories, I've added a trivial file that allows the bin directory to persist.

At this point, I think `masc` should just be pulled into the repo.  I'll do that once I have @russinoff 's permission.

**Comment by ragerdl** [comment]
Fixed by:
https://github.com/acl2/acl2/commit/c8cc11647e32afc0d29888818736b2e5d90fff86

**Comment by ragerdl** [comment]
For the record, the `bin` directory issue was fixed, but the remainder like the systemc and g++ parts have not been verified outside Intel.
