### ISSUE TITLE
Waterfall parallelism book failures

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#493]
Kaufmann reports that the following books don't work with "ACL2(p)".  I think he means "with waterfall parallelism enabled", as leeroy.defthm.com shows some of the ACL2(p) builds working on all the books.

```
std/util/tests/define.lisp
tools/soft-paper-examples.lisp
centaur/sv/svex/4vec-subtypes.lisp
centaur/sv/svex/4vmask.lisp
demos/gl-and-std/defaggregate-constants.lisp
demos/gl-and-std/defaggregate-keywords.lisp
demos/gl-and-std/defprod-constants.lisp
oracle/stv-invariant-extraction-pitfall/alu.lisp
```

Kaufmann also writes:
```
I think it's easy enough to exclude these, but what I don't know is
whether that's the right solution, or if instead the books should have
offending forms removed.  I also don't know whose job it should be to
deal with these.  It would be nice for each book owner should take
responsibility for dealing with his or her ACL2(p) failures; is that
some sort of policy?
```

WRT ^^^, I think it's unlikely that the book owners are going to deal with making sure books certify with waterfall parallelism enabled.  Also, unless we can reproduce the theory issue that prevents us from certifying the books without waterfall parallelism and then including them in an ACL2(p) session with waterfall parallelism enabled, I don't think there's an actual problem.  Let me restate:

```
The usage model for waterfall parallelism is supposed to be that you certify your books (in either of ACL2 or ACL2(p)) with waterfall parallelism disabled (which is the default setting).  And then you start ACL2(p), enable waterfall parallelism in your session when you see fit, and include the books you need.
```

Under the above model, it doesn't actually matter whether the books certify with waterfall-parallelism enabled.  So, it's kind of a moot point.

That being said, I do occasionally like to go through the books and insert the form that disables waterfall parallelism.  But this is more of a personal-hygiene issue, and it's hard to prioritize without a concrete reason.  That being said, if someone else feels like doing that, I'm very happy to approve such pull requests.  I tend to believe Matt's reports above, so an initial cut is simply to add the following form into those books:

```
  (make-event

  ; Disabling waterfall parallelism because this book allegedly uses memoization
  ; while performing its proofs.

   (if (and (hons-enabledp state)
            (f-get-global 'parallel-execution-enabled state))
       (er-progn (set-waterfall-parallelism nil)
                 (value '(value-triple nil)))
     (value '(value-triple nil))))
```

And finally, there used to be some sort of theory problem with certifying books in ACL2 and including them into an ACL2(p) session.  If someone has details on that, please open a new issue explaining how to reproduce the problem.

**Comment by MattKaufmann** [comment]
Yes, I meant that those errors occur with waterfall-parallelism enabled.

It seems to me valuable to be able to run clean ACL2(p) regressions with waterfall-parallelism enabled, for the same reason we run regressions in general: to find problems.  But I'm fine with the "usage model" put forward by David.  So I guess the right solution is the simplest, namely, to disable waterfall-parallelism for the offending books.  There are lots of examples already (see e.g. books/acl2s/cert.acl2).  I'll probably deal with this soon.  Note however that the make-event form in the preceding comment may not always be suitable, since the problem is often not about memoization (I think).  Instead, I think it's fine just to use (set-waterfall-parallelism nil) in a .acl2 file or

    (make-event
     (er-progn (set-waterfall-parallelism nil)
               (value '(value-triple nil))))

in a .lisp file, ideally with suitable comments added.

I'll probably take care of this within a few days, unless someone else does.

**Comment by ragerdl** [comment]
Thanks for doing that whenever you get to it.

When you add the form and comments to each file, could you please also add the form and comments to acl2-customization-files/README?  At some point, I'd like to go through and make all disablings the same, but that takes time....

**Comment by MattKaufmann** [comment]
I've decided to try to get this fixed tonight (it's nighttime here).  I've modified that README along the lines you suggested, David.
