### ISSUE TITLE
SV tutorial isn't included in the manual

### ISSUE THREAD

**Issue by solswords** [acl2/acl2#494]
I noticed that the SV tutorial isn't included in the manual.  This might be because they use some feature that we don't want to require for building the manual, which seems reasonable -- we might not want to require, e.g., that a user has a SAT solver available in order to build the manual.  Was there a discussion about this sort of thing at one point?

It'd be nice if we could optionally include this (and other things that use non-universal features) in the manual for users who want it.  Not sure what might be a good way to go about it -- it would be easy enough to support in ACL2, but the build system would need to cooperate too.

For future reference, to include the SV tutorial it would suffice to add to doc/top.lisp:
```
(include-book "centaur/sv/tutorial/alu" :dir :system)
(include-book "centaur/sv/tutorial/boothpipe" :dir :system)
```

**Comment by MattKaufmann** [comment]
Hi, Sol --

I usually build the manual with both glucose and quicklisp "on".
Ideally (in my opinion) glucose wouldn't be required, which should be
easy to arrange in principle (I think) simply by moving doc topics out
of the main file.  (Another advantage to that unbundling pertains to
dependencies; for example, when I fixed a typo in define.lisp, cert.pl
rebuilt many books in order to build the manual.)

In summary, I suggest adding those two include-book forms for now.
(If that suggestion doesn't make sense, then I'm missing something.)
Maybe someone will have interest and energy in seeing if glucose is
needed to build the manual as a result, and to remove that dependency
if so.

-- Matt
   Date: Tue, 25 Aug 2015 10:03:01 -0700
   From: solswords <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>

   I noticed that the SV tutorial isn't included in the manual.  This might be because they use some feature that we don't want to require for building the manual, which seems reasonable -- we might not want to require, e.g., that a user has a SAT solver available in order to build the manual.  Was there a discussion about this sort of thing at one point?

   It'd be nice if we could optionally include this (and other things that use non-universal features) in the manual for users who want it.  Not sure what might be a good way to go about it -- it would be easy enough to support in ACL2, but the build system would need to cooperate too.

   For future reference, to include the SV tutorial it would suffice to add to doc/top.lisp:
   ```
   (include-book "centaur/sv/tutorial/alu" :dir :system)
   (include-book "centaur/sv/tutorial/boothpipe" :dir :system)
   ```




   ---
   Reply to this email directly or view it on GitHub:
   https://github.com/acl2/acl2/issues/494

**Comment by solswords** [comment]
I should've been more clear.  Glucose is definitely required to build the SV tutorial, as things stand.  Also, the tutorial uses some automation to allow events that are run in the books to also be included in the manual, so it's not easy to separate the documentation from the events.

If we think most people will browse the online manual under the ACL2 homepage, and that building a manual is for advanced users (read: users who have Glucose installed) then I'll go ahead and add the include-books.  But I think someday it'd be nice to have the option, somehow, to leave those out so that users who don't have a SAT solver can still build the manual if they want to.

**Comment by MattKaufmann** [comment]
Hi, Sol --

With make-event, I think it might be reasonably straightforward to
generate those two include-book forms exactly when OS_HAS_GLUCOSE is
defined and not "".  Probably you either know what I mean or know a
reason it can't work that I'm missing -- but I'd be happy to try to
implement my suggestion if you think it makes sense and would prefer
that I do so rather than you.  (If it's to be me, though, I'd be
interested in whether or not you think I should use :check-expansion
t.)

-- Matt
   Date: Tue, 25 Aug 2015 11:21:16 -0700
   From: solswords <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>
   Cc: MattKaufmann <kaufmann@cs.utexas.edu>


   I should've been more clear.  Glucose is definitely required to build the SV tutorial, as things stand.  Also, the tutorial uses some automation to allow events that are run in the books to also be included in the manual, so it's not easy to separate the documentation from the events.

   If we think most people will browse the online manual under the ACL2 homepage, and that building a manual is for advanced users (read: users who have Glucose installed) then I'll go ahead and add the include-books.  But I think someday it'd be nice to have the option, somehow, to leave those out so that users who don't have a SAT solver can still build the manual if they want to.

   ---

**Comment by ragerdl** [comment]
Can we use a make-event to skip the inclusion of books in the way that we filter out books for the build?  I'm thinking about some of the project-specific books that I don't really need in my manuals but am very glad to see documented in the UTCS manual.

Perhaps `doc/top.lisp` should have a form named `include-book-maybe` that checks an environment variable to see whether its first argument's partial directory path matches any of the strings in that environment variable.

**Comment by solswords** [comment]
Yeah, I think it would be easy enough to rig something up with make-event.  The build system support would be somewhat more complicated, e.g. when we're using glucose we'd still need to have a dependency from doc/top.cert to centaur/sv/tutorial/alu.cert, but not when not using glucose.  So I think we'd need some sort of special support in cert.pl, which seems doable, it's just a question of what we want it to look like.

**Comment by jaredcdavis** [comment]
I generally think that the simplicity of "you must have glucose to build
the manual" is preferable to extending the build-system to support
conditional dependencies.  I could be wrong.

On Wed, Aug 26, 2015 at 9:04 AM, solswords <notifications@github.com> wrote:

> Yeah, I think it would be easy enough to rig something up with make-event.
> The build system support would be somewhat more complicated, e.g. when
> we're using glucose we'd still need to have a dependency from doc/top.cert
> to centaur/sv/tutorial/alu.cert, but not when not using glucose. So I think
> we'd need some sort of special support in cert.pl, which seems doable,
> it's just a question of what we want it to look like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/494#issuecomment-135032294>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by slobodova** [comment]
I actually disagree. If it were a tutorial about satlink, I can understand. But it is a SV tutorial that can work in BDD mode as well.
SO requiring somebody to install Glucose seems awkward.

**Comment by solswords** [comment]
I would also be totally fine with just keeping things simple and requiring glucose to build the manual.  I just hope that other people later don't add books to the manual that use software that I don't want to install.  (Or worse, that Matt doesn't want to install.)

In case we decide to tackle the conditional-include-book problem, I posted some more thoughts about it under [Issue 401](https://github.com/acl2/acl2/issues/401#issuecomment-135050363).

**Comment by MattKaufmann** [comment]
A fundamental question is:

    (Q1) Who should be able to build the manual?

I don't think I care much about the answer (as long as I can build it, in particular so that I can put it up at http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html).  For my own purposes, I'm fine with glucose being required.

But Question Q1 above is certainly pertinent to comments like Anna's.  I think that the "dispute" between Jared and Anna above might be immediately settled if there is agreement on the answer to Q1.

**Comment by MattKaufmann** [comment]
P.S. Perhaps I do have a bit of a position.  It seems to me that since it's easy to download the manual, there's normally no need for anyone to build their own copy.  So maybe the answer to Question Q1 could reasonably be: Only whoever distributes the manual needs to be able to build it.  If that's the case, then I guess I agree with Jared's position.  But maybe Anna, or someone, sees a reason to want to be able to build the manual rather than simply to download it?

**Comment by slobodova** [comment]
If you also build the manual and post it, I have no objections.

**Comment by ragerdl** [comment]
It gets a little tricky when someone builds their own internal manual
that's supposed to be a superset of the distributed manual.  I have an
opinion on this: so long as there are clear build instructions for glucose,
then I think it's fine to require such internal-manual-builders to install
glucose.

Last I checked, though, there weren't clear instructions on how to build
glucose anywhere in the world.  For me, I had to learn that I needed (1) to
make the `simp` directory and (2) that I needed to pass in the `-model`
flag to my call of `glucose-3.0/simp/glucose`.  If we put (past or future)
those instructions somewhere, then I don't think it's too much to ask a
user to install glucose.


Sure, I think you can build and use glucose without the simplifier (the
`core`), but we should have a standard approach that's easy to follow.

**Comment by MattKaufmann** [comment]
@Anna: Yes, I build it every few days (apparently even when on vacation) and post it here:

    http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html

**Comment by ragerdl** [comment]
I've got a change list in the pipeline that's going to incorrectly pronounce this issue as closed -- I'll reopen the issue once that happens.

That being said, I'd like to go ahead and include the SV tutorial. If noone objects within twenty four hours or so, I'll probably go ahead and do that.
