### ISSUE TITLE
Parse :// comments in VL

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#507]
Turns out that the `:` in a ternary operation immediately followed by a `//` for a comment isn't parsed by `VL`.  For example:

```
assign foo = a[0] ? b[0] ://
  [c]0
```

I added a `colon-example` to `books/centaur/sv/cosims`.

**Comment by jaredcdavis** [comment]
Hi,

Thanks for finding this obscure bug.  SystemVerilog adds a `:/` operator for use in distribution operators (Section 18.5.4).  When VL's lexer encounters a colon, it tries to match it against the possible operators,

 -   `:=`   distribution operator for specified weight
 -   `:/`   distribution operator for ranges
 -   `::`   package scoping operator
 -   `:`    plain colon, e.g., for ternary operators or ranges

So basically when it encounters `://`, it thinks that it has found a `:/` operator, presumably followed by an ordinary `/` divison operator, instead of a colon and a comment.

It looks like VCS and NCVerilog both instead treat this as you're expecting, so I think this is a bug with VL.  It should be pretty easy to fix this by tweaking the lexer to look for the special case of `://` and only grab the colon in that case.

Cheers,
Jared
