### ISSUE TITLE
defxdoc is ignored at the terminal until after a :doc

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#535]
The edited log shown at the end below is for the following sequence of
commands, and illustrates that defxdoc forms are ignored when
submitted before the first use of :doc (to load the deferred stuff
from xdoc/top).

    (include-book "xdoc/top" :dir :system)
    (defxdoc note-7-2 ...) ; redefines :doc note-7-2
    :doc note-7-2 ; OUCH -- doesn't pick up the redefinition!
    :doc note-7-2 ; OUCH -- still doesn't pick up the redefinition!
    (defxdoc note-7-2 ...) ; redefines :doc note-7-2, again
    :doc note-7-2 ; This time, picks up the redefinition.

The same problem occurs, by the way, if the second
":doc note-7-2" is skipped.

    ACL2 !>(include-book "xdoc/top" :dir :system)

    Summary
    Form:  ( INCLUDE-BOOK "xdoc/top" ...)
    Rules: NIL
    Time:  0.10 seconds (prove: 0.00, print: 0.00, other: 0.10)
     "/Users/kaufmann/acl2/acl2-git-scratch/books/xdoc/top.lisp"
    ACL2 !>(defxdoc note-7-2

      :parents (release-notes)
      :short "ACL2 Version  7.2 (xx, 20xx) Notes"
      :long "<p>Very short example.</p>

     ")
     (DEFXDOC NOTE-7-2)
    ACL2 !>:doc note-7-2

    TTAG NOTE (for included book): Adding ttag :XDOC from book /Users/kaufmann/acl2/acl2-git-scratch/books/xdoc/defxdoc-raw.

    TTAG NOTE (for included book): Adding ttag :READ-STRING from book /Users/kaufmann/acl2/acl2-git-scratch/books/std/io/read-string.

    ACL2 Warning [Ttags] in ( INCLUDE-BOOK "xdoc/display" ...):  The ttag
    note just printed to the terminal indicates a modification to ACL2.
    To avoid this warning, supply an explicit :TTAGS argument when including
    the book "/Users/kaufmann/acl2/acl2-git-scratch/books/xdoc/display".

    TTAG NOTE (for included book): Adding ttag :UNSOUND-EVAL from book /Users/kaufmann/acl2/acl2-git-scratch/books/xdoc/unsound-eval.

    ACL2 Warning [Ttags] in ( INCLUDE-BOOK "xdoc/display" ...):  The ttag
    note just printed to the terminal indicates a modification to ACL2.
    To avoid this warning, supply an explicit :TTAGS argument when including
    the book "/Users/kaufmann/acl2/acl2-git-scratch/books/xdoc/display".

    ACL2::NOTE-7-2 -- [books]/system/doc/acl2-doc.lisp
    Parents: RELEASE-NOTES.

      ACL2 Version 7.2 (xx, 20xx) Notes

      NOTE! New users can ignore these release notes, because the
      [documentation] has been updated to reflect all changes that are
      recorded here.
    [[ .. elided output .. ]]
      Fixed some interleaved output that could appear with
      [waterfall-parallelism] enabled. Thanks to Eric Smith for reporting
      this problem and to David Rager for a helpful chat.

    ACL2 !>:doc note-7-2
    ACL2::NOTE-7-2 -- [books]/system/doc/acl2-doc.lisp
    Parents: RELEASE-NOTES.

      ACL2 Version 7.2 (xx, 20xx) Notes

      NOTE! New users can ignore these release notes, because the
      [documentation] has been updated to reflect all changes that are
      recorded here.
    [[ .. elided output .. ]]
      Fixed some interleaved output that could appear with
      [waterfall-parallelism] enabled. Thanks to Eric Smith for reporting
      this problem and to David Rager for a helpful chat.

    ACL2 !>(defxdoc note-7-2

      :parents (release-notes)
      :short "ACL2 Version  7.2 (xx, 20xx) Notes"
      :long "<p>Very short example.</p>

     ")
     (DEFXDOC NOTE-7-2)
    ACL2 !>:doc note-7-2
    ACL2::NOTE-7-2 -- Current Interactive Session
    Parents: RELEASE-NOTES.

      ACL2 Version 7.2 (xx, 20xx) Notes

      Very short example.

    ACL2 !>

**Comment by jaredcdavis** [comment]
Hi,

I think I understand why this happens and there should be an easy workaround
that fixes it and speeds things up slightly (on CCL).

Recall that xdoc topics are just stored in a table, and that you can freely
smash any topic at any time you like by issuing a `defxdoc` command.  But
the
first time a `:xdoc` command is issued (or a `:doc` command after `xdoc/top`
has been loaded, since `xdoc/top` smashes `:doc` with `:xdoc`), it issues a
special command called `colon-xdoc-init`.  This command loads the code that
is
necessary to display xdoc topics, and also loads the `system/doc/acl2-doc`
book
to populate the xdoc database with the system documentation.

But, the inclusion of this `acl2-doc` book causes the submission of many
`defxdoc` commands, including in particular the topic for `note-7-2`, so
your
version of `note-7-2` is getting smashed because you are (inadvertently)
overwriting when you (implicitly) load the system documentation from its
book.

I think the workaround is to change `colon-xdoc-init` to load the book
`system/doc/acl2-doc-wrap` instead of the book `system/doc`.  This wrapper
book
is careful to install the system documentation "behind" any existing
documentation.  Also, it's faster to load because it reads in all the docs
from
a make-event expansion and doesn't have to do any defxdoc form processing.

Well, faster on CCL at least.  Oddly it looks like loading `acl2-doc-wrap`
is a
bit slower than loading `acl2-doc` on SBCL.  I don't know why.  I'll make
this
change and include it in my next push (which may be awhile because I have a
lot
of stuff outstanding).  If you want to make it before then, it's really
easy,
just change the `include-book` in `colon-xdoc-init` (found in `xdoc/top`) to
load `system/doc/acl2-doc-wrap` instead of `system/doc/acl2-doc`.

Cheers,
Jared


On Fri, Oct 30, 2015 at 10:00 AM, MattKaufmann <notifications@github.com>
wrote:

> Assigned #535 <https://github.com/acl2/acl2/issues/535> to @jaredcdavis
> <https://github.com/jaredcdavis>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/535#event-450475183>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by MattKaufmann** [comment]
Thanks, Jared -- that makes sense.  No hurry on my account -- I can easily work around this in the meantime (sorry, I should have said that up front).

While you're at it, perhaps you'd be willing to add an appropriate call of set-deferred-ttag-notes to reduce the noise from that initial :doc command.  But maybe it's not worth the trouble (there's still some noise).

**Comment by jaredcdavis** [comment]
That would be nice but I don't know how to do it... it doesn't seem like `set-deferred-ttag-notes` is embeddable, and when I try to do it in the `make-event` as shown below, it doesn't seem like it affects the subsequent forms.

```
(defmacro colon-xdoc-init ()
  '(with-output :off (summary event observation prove proof-tree)
     (make-event
      (if (acl2::colon-xdoc-initialized state)
          (value '(value-triple :invisible))
        (mv-let (er val state)
          (set-deferred-ttag-notes t state)
          (declare (ignore er val))
          (value `(progn
                    (include-book ;; newlines to fool dependency scanner
                     "xdoc/defxdoc-raw" :dir :system :ttags :all)
                    (include-book
                     "xdoc/topics" :dir :system)
                    (include-book
                     "system/doc/acl2-doc-wrap" :dir :system)
                    (include-book
                     "xdoc/display" :dir :system)
                    (encapsulate ()
                      (local (xdoc-quiet)) ;; Suppress warnings when just using :xdoc (or :doc)
                      (local (set-inhibit-warnings "Documentation")))
                    (table xdoc 'colon-xdoc-support-loaded t))))))))
```

**Comment by jaredcdavis** [comment]
It looks like adding `:ttags :all` to the xdoc/display include cuts the ttag notes down pretty well (deferring them actually makes it worse because it prints so much stuff.)

**Comment by MattKaufmann** [comment]
Added ability to use set-deferred-ttag-notes during make-event expansion (see comment before last) in commit 55cb625fc900812db6446fe4148edbb120d3bf5a.
