### ISSUE TITLE
Raw Lisp error (harmless?) during certification of books/centaur/vl2014/kit/top.lisp using SBCL

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#634]
I noticed today that when certifying the book

    books/centaur/vl2014/kit/top.lisp

using ACL2 built on SBCL 1.3.5 in Linux, the file
top.cert.out included a backtrace from a raw Lisp error.
Perhaps surprisingly: in spite of that error, the book
certified successfully, and also I could subsequently
include it successfully, but also with a backtrace for the
include-book.

I've attached logs showing the two backtraces (when running
certify-book and include-book for the book mentioned above).
[log-certify-book.txt](https://github.com/acl2/acl2/files/426226/log-certify-book.txt)
[log-include-book.txt](https://github.com/acl2/acl2/files/426228/log-include-book.txt)

**Comment by jaredcdavis** [comment]
Hi,

I think that's provoked by the explicit test to make sure that the
vls-try-catch error handler in centaur/vl2014/server/server-raw.lsp is
working.

If you look at the code for vls-error-handler, it's trying to redirect
the backtrace to a temporary binding of *debug-io* instead of printing
it.  Maybe something changed with the way that
acl2::print-call-history works and this rebinding needs to be somehow
updated?

Cheers,
Jared


On Thu, Aug 18, 2016 at 9:38 PM, MattKaufmann <notifications@github.com> wrote:
> I noticed today that when certifying the book
>
> books/centaur/vl2014/kit/top.lisp
>
> using ACL2 built on SBCL 1.3.5 in Linux, the file
> top.cert.out included a backtrace from a raw Lisp error.
> Perhaps surprisingly: in spite of that error, the book
> certified successfully, and also I could subsequently
> include it successfully, but also with a backtrace for the
> include-book.
>
> I've attached logs showing the two backtraces (when running
> certify-book and include-book for the book mentioned above).
> log-certify-book.txt
> log-include-book.txt
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Jared C. Davis <jared.c.davis@gmail.com>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by MattKaufmann** [comment]
Thanks for the tip.  I've assigned it to myself, to look at sometime; anyone who needs this fixed is welcome to ask me to bump up the priority.

**Comment by MattKaufmann** [comment]
Fixed in commit 6d7ad53ecdaaec9dcf3e3d05c19832b97fa7062a.
