### ISSUE TITLE
Note printed on screen when including books/centaur/fty/top.lisp

### ISSUE THREAD

**Issue by acoglio** [acl2/acl2#668]
When including "centaur/fty/top" from :dir :system, the following gets printed on screen:

Note: not introducing any FLEXTRANSSUM-MEMBER field bindings for MEMBER,
since none of its fields appear to be used.

Matt noted that this may come from books/std/util/da-base.lisp.

Is it necessary for this message to be printed? It seems a bit odd to me, given that I'm just including a library, but perhaps there's a good reason for it or it would be inconvenient to remove.

**Comment by solswords** [comment]
I've gotten used to seeing lots of such messages, because I'm not very careful about fixing them in my own code.   This one appears to be from visitor-transsum-member-body -- just because we bind member as a flextranssum-member but then don't use any of its fields.  It's basically harmless, but I could see how it'd be annoying if you actually pay attention to things that are printed on your screen, so feel free to fix it, or I will eventually.

It might be nice if that message had more context or could be inhibited somehow, but since it's during macroexpansion that we notice this, we can't access anything other than the macro arguments and can't update state or do much besides just print a dumb message.  I sometimes think it shouldn't bother.

**Comment by acoglio** [comment]
It looks like this is no longer an issue. Thanks, Keshav.

**Comment by kini** [comment]
Actually, @solswords, why don't we make this into an actual error instead of a warning? That'll stop the warnings from cropping up. I just realized that it's basically analogous to the errors that ACL2 itself gives when you bind a variable in a `let` but don't use it.

**Comment by solswords** [comment]
Hi @kini -- I'd be basically OK with it being an error, but it's
potentially a backward compatibility headache.  If you want to do it and
fix the problems that crop up in the community books, I guess I'd say go
for it.  There needs to be a way to turn off the error (per use of the
macro -- unfortunately there can't really be a global switch due to state
not being accessible) and that would need to be used in a few places where
binders are automatically generated for code that may or may not use them
(the foo-case macro for fty sum types comes to mind but there may be
others).

There are maybe some subtleties to think about, though -- might be times
when it's less obviously wrong than others.  E.g.
(b* (((my-type x) (some-term ...)))
   ... body that uses x but not x.anything...)
The binder still binds x to (some-term ...) and conveys that x is supposed
to be of my-type -- it may or may not be a mistake that none of the fields
of x are used.
