### ISSUE TITLE
Quicklisp failure with CMUCL; perhaps just update :doc quicklisp

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#669]
I've encountered a regression failure, as reported in
books/centaur/quicklisp/base.cert.out.  The command was as follows.

    make -j 8 regression-fresh USE_QUICKLISP=1 ACL2=<some_path>/cmucl-saved_acl2

My understanding has been that ACL2 should work with quicklisp unless
the host Lisp is GCL; however, :doc quicklisp doesn't seem to mention
the host Lisps for which quicklisp is or is not supported with ACL2.
Perhaps it's not important to get CMUCL to work with quicklisp, but at
any rate it would be good to update :doc quicklisp with a list of
supported, or unsupported, Lisps.

Here is the relevant part of base.cert.out.

    HARD ACL2 ERROR in INCLUDE-RAW:  Load of "base-raw.lsp" failed with
    the following message:

    Error in function CFFI-GROVEL:GROVEL-ERROR:
       External process exited with code 1.
    Command was: "cc" "-m32" "-I/v/filer4b/v11q002/acl2space/acl2/devel/books/cent\
    aur/quicklisp/bundle/software/cffi_0.16.1/" "-o" "/v/filer4b/v11q002/acl2space\
    /acl2/devel/books/centaur/quicklisp/asdf-home/cache/common-lisp/cmu-
    snapshot-2016-01__21a_unicode_-linux-x86/v/filer4b/v11q002/acl2space/acl2/deve\
    l/books/centaur/quicklisp/bundle/software/osicat-20150709-git/posix/basic-
    unixint" "/v/filer4b/v11q002/acl2space/acl2/devel/books/centaur/quicklisp/asdf-
    home/cache/common-lisp/cmu-snapshot-2016-01__21a_unicode_-linux-x86/v/filer4b/\
    v11q002/acl2space/acl2/devel/books/centaur/quicklisp/bundle/software/osicat-
    20150709-git/posix/basic-unixint.c"
    Output was:
    /v/filer4b/v11q002/acl2space/acl2/devel/books/centaur/quicklisp/asdf-
    home/cache/common-lisp/cmu-snapshot-2016-01__21a_unicode_-linux-x86/v/filer4b/\
    v11q002/acl2space/acl2/devel/books/centaur/quicklisp/bundle/software/osicat-
    20150709-git/posix/basic-unixint.c:10:23: fatal error: sys/types.h:
    No such file or directory
     #include <sys/types.h>
			   ^
    compilation terminated.

I'm assigning this to Jared because I think he's our "quicklisp guy", but
of course I'd be happy for anyone knowledgeable to take this on.

**Comment by jaredcdavis** [comment]
Per the error message I think this looks like some missing C libraries.
(Sys/types.h). There may be an easy apt-get or similar command you can run
to get the needed libraries.  I'm not sure offhand what it is, though...

**Comment by MattKaufmann** [comment]
Thanks, Jared.  I've tried LispWorks today, and there's no problem there.
Also, I've been doing lots of SBCL and CCL regressions with quicklisp;
no problem there either.  I don't much care about CMUCL with quicklisp,
so you can close this if you like as far as I'm concerned.  But I'd really
appreciate advice on improving :doc quicklisp to clarify what's expected.
I could add that we expect it to work on all Lisps except GCL, but in
some cases it may be necessary to install missing C libraries.  Would
that be reasonable, or do you have any better ideas?

**Comment by jaredcdavis** [comment]
Hi,

I think it's the case that Quicklisp itself, and several basic
Quicklisp libraries, such as (say) alexandria, are pure Lisp
code and should not require anything other than a non-GCL
lisp.

However, there are other important Quicklisp libraries, such
as cffi (a C foreign function interface) and osicat (os and
file system utilities), that require a C compiler and some
basic C libraries.  These libraries are required by certain
ACL2 books (most notably oslib) and also by other Quicklisp
libraries such as hunchentoot which is used in, e.g., the VL
server.

For most Linux users, it should hopefully be very easy to
install the required C libraries using a package manager like
apt-get or yum to install the appropriate packages.

It would (of course) be nice to document what is required.
But that might not be easy.  I don't know of any easy way to
find out what packages are actually needed.  I think on the
Debian, Ubuntu, Mint, etc., you may at least need packages
with names like "build-essential" or "libc-dev" or similar.
But the particular package names and methods for installing
them depends on the OS.

Since this looks like a missing C library, I don't know how it
could be that you are successfully building these libraries
with Lisps like SBCL or Lispworks but not on CMUCL.  As a shot
in the dark, maybe it's because CMU is a 32-bit Lisp and the
others are 64-bit?  Perhaps you need a 32-bit version of these
libraries, perhaps something like libc-dev-i386?

I think that it should be possible, in principle, for most of
the Quicklisp books to certify on all ACL2 host lisps except
for GCL.  In cases where a certain Quicklisp library doesn't
work on one Lisp or another, I think we have marked the
corresponding books with cert-params like "non-cmucl".  So, as
a general expectation, if the build system tries to build
something, the belief is that it should be possible to build
it on your current Lisp.

Thanks,
Jared


On Sun, Nov 6, 2016 at 6:59 PM, MattKaufmann <notifications@github.com> wrote:
>
> Thanks, Jared. I've tried LispWorks today, and there's no problem there.
> Also, I've been doing lots of SBCL and CCL regressions with quicklisp;
> no problem there either. I don't much care about CMUCL with quicklisp,
> so you can close this if you like as far as I'm concerned. But I'd really
> appreciate advice on improving :doc quicklisp to clarify what's expected.
> I could add that we expect it to work on all Lisps except GCL, but in
> some cases it may be necessary to install missing C libraries. Would
> that be reasonable, or do you have any better ideas?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.




-- 
Jared C. Davis <jared.c.davis@gmail.com>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by MattKaufmann** [comment]
I expect to update :doc quicklisp within soon (maybe today) by adding
the following lines to the paragraph in :doc quicklisp starting with:
"Note that the Quicklisp books".

    However, every ANSI-compliant host Common Lisp suitable for ACL2 should support
    the use of Quicklisp, where occasionally libraries may need to be installed.
    As of late 2016, all host Common Lisp implementations suitable for ACL2 are
    sufficiently ANSI-compliant for the use of Quicklisp except for GCL.

I'll close this Issue when I do that.  Of course, anyone who prefers a
different update to the :doc is welcome to make it.

**Comment by MattKaufmann** [comment]
Closing as promised above, with commit 7bff925dcf6d07a830820615dba973e7d5e70aa4.
See:

    http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=ACL2____QUICKLISP
