### ISSUE TITLE
Inconsistent comments in cert.pl about where the books are

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#749]
In early section of the comments in cert.pl, we read:

```
# This script assumes that the ACL2 system books directory is where it
# itself is located.  Therefore, if you call this script from a
# different directory, it should still be able to resolve ":dir
# :system" include-books.  It also scans the relevant .acl2 files for
# each book for add-include-book-dir commands.
```

Then later at line 636, we read:

```
# If $acl2_books is still not set, then try the following in order
# until one succeeds:
#   - set it based on the location of acl2 in the path
#   - set it by running acl2 and dumping (@ system-books-dir)
#   - set it to the parent of the directory containing this script.
```

I haven't fully read the code but it seems to me that the second 
section of comments is more true than the first section. According
to my experience, $acl2_books will only gets set before the second
section of comments if the option --acl2-books is set or if the
environment variable $ACL2_SYSTEM_BOOKS is set. Otherwise,
it follows whats described in the second comment.

If that's really the case, should we remove the first comments and
move the second to the beginning with below changes?

```
# If $acl2_books is set in below order until one succeeds:
#   - set it based on cert.pl option --acl2-books
#   - set it based on environment variable $ACL2_SYSTEM_BOOKS
#   - set it based on the location of acl2 in the path
#   - set it by running acl2 and dumping (@ system-books-dir)
#   - set it to the parent of the directory containing this script.
```

**Comment by kini** [comment]
Thanks for the report. I actually just talked to Ian about this about an hour ago and I'm looking at it right now :)

The second section of comments was recently updated by me in #707, which is probably why it seems more accurate than the other comment, which I failed to notice and update.

**Comment by solswords** [comment]
You're certainly right that the first comment is wrong; I think the second
comment is right, but it just doesn't deal with what's above that point in
the file (which could set it based on command line option or environment
variable).  I'd rather not move the comment to the beginning, though,
because I like have a comment near the code that actually sets the variable
saying what it's doing, though, so I'd rather not move that comment to the
beginning.  Maybe this should also be explained in the --help -- it's
alluded to when describing the --acl2-books option but not explained, and I
don't think the xdoc discusses it either.

**Comment by pennyan** [comment]
Hi~ @solswords , good ideas putting the explanation into --help and the xdoc. Fully supported!
