### ISSUE TITLE
Make two manual build targets, one for z3+glucose and one for neither

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#824]
Some are frustrated that there's no way to build the manual without `glucose`.  There's also discussion of making the current situation worse by also requiring `z3`.  This issue proposes that we create two manuals:

(1) One that requires neither `glucose` nor `z3`, and
(2) One that requires both `glucose` and `z3`

If you'd like (1), then feel free to record that here.  Also, if interested, please include whether you have the time and inkling to implement it.

Related to #789

**Comment by MattKaufmann** [comment]
Below is a proposal that I think synthesizes what people want: be able
to build a version of the manual based on which tools are installed.
In summary: it requires annotation of books/doc/top.lisp with
dependencies on external tools, and it generates a different file to
build the manual.

I'll wait till after tomorrow to see if at least a couple of people
like this and nobody really objects.  In that case I'll probably work
on this over the weekend.

Note: I realize that cert.pl generates books/build/Makefile-deps,
which lists books under CERT_PL_USES_GLUCOSE.  So in principle there
could perhaps be more automation than is proposed below, to avoid the
required annotations.  But I'm trying to propose something that is
pretty easy for me to do.  If someone wants to do this differently,
that's certainly fine with me!  But if someone insists on more
automation then I probably won't do this alone.  Besides, I think it
would be kind of nice to make the external dependencies explicit in
doc/top.lisp with the proposed annotations.

(1) The commands near the end of books/doc/top.lisp will be moved to a
different file, books/doc/manual-build.lsp, that is not a book (we'll
see below how it is used).

(2) Books in books/doc/top.lisp that depend on external tools will get
corresponding annotations as stylized comments, e.g.:

    (include-book "centaur/sv/tutorial/alu" :dir :system) ; <uses glucose>

(3) A new target will be added to books/GNUmakefile: doc/manual.lisp.
This will be a file that is generated by excluding the appropriate
include-book forms and then appending (to the end) the contents of
books/doc/manual-build.lsp (see (1) above).  I'll have to work out how
to ensure that doc/manual.lisp is regenerated and also certified by
the "manual" and "everything" targets.  This will depend on handing
OS_HAS_Z3 in analogy to how OS_HAS_GLUCOSE is currently handled.
Here's some untested code for the proposed new target.

    doc/manual.lisp:
    ifeq ($(OS_HAS_GLUCOSE), )
        fgrep -v '; <uses glucose>' doc/top.lisp > doc/tmp1
    else
        cp -p top.lisp tmp1 ;\
    endif
    ifeq ($(OS_HAS_Z3), )
        fgrep -v '; <uses z3>' doc/tmp1 > doc/tmp2.lisp
    else
        cp -p doc/tmp1 doc/tmp2.lisp ;\
    endif
        cat doc/tmp2.lsp doc/manual-build.lsp > doc/manual.lisp
        rm doc/tmp1 doc/tmp2

(4) Anyone is welcome to add more dependencies on external tools by
editing the GNUmakefile text in (3), and also adding the definition of
OS_HAS_<tool> in analogy to how OS_HAS_GLUCOSE is currently defined in
GNUmakefile.  In particular, Yan Peng can add z3 books this way.

**Comment by solswords** [comment]
Hi Matt,

This sounds fine to me, in principle.

Step (3) sounds a little tricky to implement in the makefile -- maybe you
have another idea of how to do it, but I think it boils down to either (a)
building manual.lisp on basically every make invocation -- which might be a
little annoying because it would always appear to need recertifying, even
if none of its dependencies did -- or (b) building manual.lisp only if it's
missing or doc/top.lisp changes, which means if a user installs glucose or
z3 they have to know to delete it before proceeding -- which I guess would
be a fine thing to just put in some documentation.

I had suggested a slightly different route, where we add an ifdef-like
macro and add support for scanning it in cert.pl, so that doc/top could
have its dependencies generated directly and be certified directly.  I
still think this is a good option, though I realize I'd probably be the one
to implement it in this case and someone else might get around to doing
something else first.  I think this would have to look something like this:
(ifenv "OS_HAS_GLUCOSE"
  (include-book "foo")
  (include-book "bar")
  endif) ; nonsense symbol required for cert.pl scanning

I think I'd prefer either of these to (say) statically having doc/top.lisp
and doc/top-with-glucose-and-z3.lisp that need to be maintained separately.
I also would like to still have the option to build a manual with glucose
but not z3.

- Sol

**Comment by MattKaufmann** [comment]
Sol, I think we're thinking along the same lines.  I should have
mentioned that I'm perfectly happy with your proposal (which probably
inspired mine, at least at some level of consciousness).  The problem,
which you identified, is that you'd probably be the one to carry out
the cert.pl modifications.  My comment was kind of inspired by a
desire to get all this resolved so that Yan Peng can proceed with her
integration of the Satlink documentation into the acl2+books manual.
I proposed starting on that this weekend.

So a question is: Do you want to take a crack at your proposal, and if
so, when would you expect to get to it?  Otherwise, I'm still happy to
work on my proposal.

Speaking of which: Yes, this is what I guess I had in mind (to the
extent that I'd thought it out):

> (b) building manual.lisp only if it's missing or doc/top.lisp changes,

So instead of

    doc/manual.lisp:

I should have written:

    doc/manual.lisp: doc/top.lisp doc/manual-build.lsp

I figure that those relatively few people who build the manual can
reasonably be expected to remove doc/manual.lisp after installing a
new external tool -- and as you say, that "would be a fine thing to
just put in some documentation."  Actually, your proposal would have
the same issue, I think.  For my own purposes I'm not concerned, since
I clean the books often, and I'd extend the "clean" target to delete
doc/manual.lisp.

**Comment by solswords** [comment]
OK, I'll give it a try and get back to you if I won't be able to get it
done in a timely manner.

**Comment by MattKaufmann** [comment]
Thanks, Sol.  I expect to be available to do this if that doesn't work
out.

-- Matt
