### ISSUE TITLE
Unnecessary TTAG in centaur/defrstobj?

### ISSUE THREAD

**Issue by david-s-hardin** [acl2/acl2#832]
I have been using centaur/defrstobj for a project utilizing ACL2 8.0, and have found it odd that it requires the use of a TTAG, namely :FAST-CAT from books/std/strings/fast-cat.  My understanding is that :FAST-CAT exists to improve string concatenation speed, which is all well and good.  However, the use of :FAST-CAT in defrstobj arises, as far as I can tell, from the inclusion of the book centaur/misc/introduce-var in def-typed-record.lisp and typed-records.lisp (N.B. introduce-var includes the aforementioned optimized string book via a tortured path through centaur/vl, if my understanding is correct)...but, the introduce-var function is only called in the body of theorem definitions, namely equal-of-tr-set in typed-records.lisp, and a theorem-generating macro in def-typed-record.lisp.  As far as I can determine, no function in defrstobj calls any of the fast-cat routines.  (I've tried tracing the fast-cat routines, and they're never called during the execution of my project code.)

I find it very strange and off-putting that I have to accept a trust tag introduced in the name of speed only, and it is only being used in the statement of theorems (as far as I can tell).  I request that the authors of the books mentioned in this note re-examine this situation, and perhaps refactor things s.t. the trust tag is no longer required.  I will eventually submit the book I am currently working on to a DoD customer, and I'd like it to be free of any ACL2 modifications, minor though they may be.

Thanks,

David Hardin

**Comment by ragerdl** [comment]
I'm curious what @solswords might say, since he's more familiar with the centaur directories.  That being said, maybe it makes sense for @MattKaufmann to incorporate `fast-cat` into ACL2 proper.  I tend to agree that `defrstobj` would be good to use without requiring a `ttag`.  Would the OP (original poster [david-s-hardin]) be willing to submit a patch if the community was okay with lower performance?

**Comment by jaredcdavis** [comment]
Hi,

This seems like an easily fixable bug.

The introduce-var book can (and should) almost surely be changed to
just include "std/strings/cat" instead of the fast-cat to avoid the
unnecessary trust tag.  Fast-cat is purely a performance boost that
adds no logical definitions and can be included at any time it is
desired (i.e., there is no reason to ever include it until you really
want it).

Building this optimization into ACL2 is a perfectly fine idea.  But on
the other hand, arguably it's something that Common Lisp compilers
should just optimize for anyway...

Cheers,
Jared

On Tue, Apr 3, 2018 at 6:33 PM, David L. Rager <notifications@github.com> wrote:
> I'm curious what @solswords might say, since he's more familiar with the
> centaur directories. That being said, maybe it makes sense for @MattKaufmann
> to incorporate fast-cat into ACL2 proper. I tend to agree that defrstobj
> would be good to use without requiring a ttag. Would the OP (original poster
> [david-s-hardin]) be willing to submit a patch if the community was okay
> with lower performance?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Jared C. Davis <jared.c.davis@gmail.com>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by david-s-hardin** [comment]
>Would the OP (original poster [david-s-hardin]) be willing to submit a
patch if the community was okay with lower performance?

That's the weird thing -- I don't think performance would be any lower,
since the optimized functions in question are not called by any function in
defrstobj, but only in some theorem statements...unless I'm missing
something.


DSH

**Comment by MattKaufmann** [comment]
Just a quick reply to this comment from @ragerdl:

    That being said, maybe it makes sense for @MattKaufmann to
    incorporate fast-cat into ACL2 proper.

I tend to agree with the @jaredcdavis comment that this is really a
Common Lisp issue, so I'm not inclined to try to change ACL2 to
incorporate fast-cat.  I haven't thought about what would be involved,
but at first glance it might not quite be trivial; one comment in
books/std/strings/fast-cat.lisp says that performance has only been
tested in CCL, and another suggests a possible memory issue:

    ; And indeed (- 1760 1280) is 480.  So it looks like CCL's concatenate is
    ; somehow able to avoid consing its arguments into a list like our
    ; fast-concatenate macro is doing.

**Comment by solswords** [comment]
I think as Jared said it'd be fine to include just cat rather than fast-cat
in lower-level books -- we just want it to be around when we start actually
executing things where string concatenation speed might matter for
performance.

How about an experiment: change the un-ttagged definitions of
fast-string-append(-lst) so that they print a warning when they're run,
change the includes of fast-cat to just cat in vl/defs and vl-2014/defs,
and grep all the .cert.out files after recertifying to see where they get
executed?

**Comment by david-s-hardin** [comment]
Yes, this would be a very interesting experiment.  Personally, I wouldn't want to include a TTAG'ed book from such an oft-included book as centaur/vl/defs (at least I'm guessing it's commonly included) unless I had to for functionality reasons, or it made a significant global performance difference.  The problem is that the TTAG ends up getting propagated into lots of places, including some very peculiar ones, such as defrstobj.  In my view, we should be more careful about propagating TTAGS throughout the ACL2 books.  In addition to the obvious trust issues, the propagation of TTAGS is also an indicator that perhaps a coupling exists between otherwise unrelated books that shouldn't be there.  Tight coupling is a common problem in library development for any language, and scrubbing one's libraries (books) to reduce undesired coupling is just good software engineering practice.

**Comment by david-s-hardin** [comment]
Looks like Sol has committed the necessary adjustments to decouple fast-cat from centaur/vl/defs -- many thanks!


DSH
